// app/layout.jsx (Next.js 13+)
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// Import Poppins
const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["300", "400", "500", "600", "700", "800", "900"], // optional: select weights you need
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#363636",
              color: "#fff",
            },
            success: {
              iconTheme: {
                primary: "#10b981",
                secondary: "#fff",
              },
            },
            error: {
              iconTheme: {
                primary: "#ef4444",
                secondary: "#fff",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
